[workspace]

[package]
name = "twitch-adapter-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cockatiel-client = { git = "https://github.com/vulbyte/cockatiel_client-rs", rev = "59920409d5643942c94a23753febcaa0c3a9817e" }
tokio = { version = "1.38", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
open = "5.0"
reqwest = { version = "0.11", features = ["json"] }
prost = "0.14"
uuid = { version = "1", features = ["v7"] }
